const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const context=vm.createContext({console});
for(const name of ['knowledge','indicators','patterns','engine'])vm.runInContext(fs.readFileSync(__dirname+'/../public/'+name+'.js','utf8'),context);
const {Engine,TA}=vm.runInContext('({Engine,TA})',context);
const fixture=require('./fixtures');
const original=fixture();
const candles=original.map(c=>({...c,o:300-c.o,h:300-c.l,l:300-c.h,c:300-c.c}));
const A=TA.analyzeSeries(candles),higher={latest:{price:100,sma20:120},structure:{trend:'downtrend'}};
const asset={candles,price:candles.at(-1).c,isCrypto:false,type:'EQUITY',side:'short',dailyTurnover:1e9};
const r=Engine.assess(asset,A,higher,{regime:'risk-off'},Engine.TF_INTRADAY);
assert.equal(r.side,'short');assert.equal(r.checks[1].pass,true);assert.equal(r.checks[2].pass,true);
assert(r.candidates.length>0,'Synthetic range must produce a short candidate');
assert(r.plan,'Synthetic retest must produce a plan');
assert(r.plan.stop>r.plan.entryHigh);assert(r.plan.targets[0].price<r.plan.entryLow);
assert(Math.abs(r.plan.rr1-(r.plan.entryHigh-r.plan.targets[0].price)/(r.plan.stop-r.plan.entryHigh))<1e-8);
const bullish=Engine.assess(asset,A,higher,{regime:'risk-on'},Engine.TF_INTRADAY);
assert.equal(bullish.status,'blocked');
const stale=Engine.assess({...asset,dataIssue:'stale'},A,higher,{regime:'risk-off'},Engine.TF_INTRADAY);
assert.equal(stale.status,'unavailable');
const swing=Engine.assess(asset,A,higher,{regime:'risk-off'},Engine.TF_SWING);assert.equal(swing.status,'blocked');
const size=Engine.positionSize(100000,1,100,105,{side:'short',costBps:0});assert.equal(size.units,100);assert.equal(size.riskAmt,500);
assert.equal(Engine.positionSize(100000,1,100,95,{side:'short'}),null);
assert(Engine.positionSize(100000,1,100,95,{side:'long'}));
console.log('Direction tests passed: bearish retest, stop/target ordering, R:R, tide, stale data, short scope and sizing.');
const perp={...asset,isCrypto:true,type:'PERPETUAL',liquidity:null,venueVolume24h:2e6};
const pr=Engine.assess(perp,A,higher,{regime:'risk-off'},Engine.TF_INTRADAY);
assert.notEqual(pr.status,'unavailable');assert.equal(pr.liquidityOK,true);
const missing=Engine.assess({...perp,venueVolume24h:undefined},A,higher,{regime:'risk-off'},Engine.TF_INTRADAY);
assert.equal(missing.status,'unavailable');
const spot=Engine.assess({...perp,type:'CRYPTOCURRENCY',liquidity:2e6},A,higher,{regime:'risk-off'},Engine.TF_INTRADAY);
assert.equal(spot.status,'blocked');
console.log('Perpetual checks passed: venue volume, missing feed, no spot short eligibility.');
